User.create!([
  {email: "zach@firstexitmedia.com", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-11-20 22:21:51", last_sign_in_at: "2015-11-18 21:52:44", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: nil},
  {email: "zacharyalevy@gmail.com", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 18, current_sign_in_at: "2015-11-25 15:46:40", last_sign_in_at: "2015-11-24 23:23:51", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: true},
  {email: "zacharyalevy+test001@gmail.com", password: "password", password_confirmation: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2015-11-25 17:00:20", last_sign_in_at: "2015-11-25 16:14:27", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: nil}
])
Profile.create!([
  {name: "Siva Real Estate", video_url: "5224064", representitive: "Soniya ", phone: "416 400 0444", category_id: 2, user_id: 2, facebook: "", twitter: "", instagram: "", address: "815 - 38 Dan Leckie Way, Toronto, ON", lat: 43.6374919, lng: -79.3979466, thumbnail_url: "https://i.vimeocdn.com/video/16212575_640.jpg", description: nil},
  {name: "Rachael", video_url: nil, representitive: "", phone: "", category_id: 2, user_id: 4, facebook: "", twitter: "", instagram: "", address: "", lat: nil, lng: nil, thumbnail_url: nil, description: nil},
  {name: "First Exit Media", video_url: "tUu8hSiQXFM", representitive: "Zach Levy", phone: "647 667 5215", category_id: 1, user_id: 1, facebook: "zacharyaaronlevy", twitter: "zachary_levy", instagram: "", address: "1701 - 55 Maitland St, Toronto, ON", lat: 43.6642168, lng: -79.3815091, thumbnail_url: "https://img.youtube.com/vi/tUu8hSiQXFM/mqdefault.jpg", description: "great #number of #tags here #bro #nice"}
])
Category.create!([
  {name: "Business"},
  {name: "Real Estate"}
])
Conversation.create!([
  {sender_id: 1, receiver_id: 2, message: "cool story bro", read: false},
  {sender_id: 1, receiver_id: 2, message: "", read: false},
  {sender_id: 1, receiver_id: 2, message: "hey were meeting", read: true},
  {sender_id: 1, receiver_id: 2, message: "hey", read: nil},
  {sender_id: 1, receiver_id: 2, message: "asfasdfafasdfas", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0003", read: nil},
  {sender_id: 1, receiver_id: 2, message: "test0004", read: nil},
  {sender_id: 4, receiver_id: 1, message: "hey", read: nil},
  {sender_id: 4, receiver_id: 1, message: "Hey, what's up?", read: true},
  {sender_id: 4, receiver_id: 1, message: "hey!", read: nil},
  {sender_id: 4, receiver_id: 1, message: "hey!", read: true}
])

Notification.create!([
  {message: "You have a new message from Rachael.", link: "/conversations/25", profile_id: 1},
  {message: "Rachael followed you.", link: "/profiles/4", profile_id: 1},
  {message: "Rachael added you as a partner.", link: "/profiles/4", profile_id: 1},
  {message: "Rachael added you as a partner.", link: "/profiles/4", profile_id: 1}
])
Page.create!([
  {html: "<p>ok</p>", slug: "about"}
])
Post.create!([
  {image_url: "https://ucarecdn.com/c0855e46-c926-4a98-ab3b-9a9b2ebca87d/", video_url: nil, description: "", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "https://ucarecdn.com/e4c7796e-78ac-4b0e-80a0-33f19e8834a5/-/crop/1412x917/171,163/-/preview/", video_url: nil, description: "", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "https://ucarecdn.com/f8ff470b-82f4-4b31-a941-725691408014/", video_url: nil, description: "new promotion", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "ok", profile_id: 1, thumbnail_url: nil, post_category_id: 1, mention_id: 2},
  {image_url: "", video_url: nil, description: "normal post", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "ok sweet http://google.com/?ref=idk", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "First", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "great place", profile_id: 4, thumbnail_url: nil, post_category_id: 1, mention_id: 1},
  {image_url: "", video_url: "HK0pBDZiWgk", description: "great description", profile_id: 1, thumbnail_url: "https://img.youtube.com/vi/HK0pBDZiWgk/sddefault.jpg", post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: "WOVEy1tC7nk", description: "", profile_id: 1, thumbnail_url: "https://img.youtube.com/vi/WOVEy1tC7nk/sddefault.jpg", post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "rem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing softw", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: "106365480", description: "Burning man video!", profile_id: 1, thumbnail_url: "https://i.vimeocdn.com/video/489785085_640.jpg", post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "asdf", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "asdf", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil},
  {image_url: "", video_url: nil, description: "asdfas", profile_id: 1, thumbnail_url: nil, post_category_id: nil, mention_id: nil}
])
PostCategory.create!([
  {name: "review"},
  {name: "job"},
  {name: "status"},
  {name: "portfolio"},
  {name: "promotion"}
])
Tag.create!([
  {name: "money"},
  {name: "winning"},
  {name: "code"},
  {name: "condos"},
  {name: "pre-construction"},
  {name: "business"},
  {name: "#number"},
  {name: "#tags"},
  {name: "#bro"},
  {name: "#nice"},
  {name: "number"},
  {name: "tags"},
  {name: "bro"},
  {name: "nice"}
])
Partner.create!([
  {profile_id: 2, partner_id: 1},
  {profile_id: 1, partner_id: 1},
  {profile_id: 4, partner_id: 1}
])
Friend.create!([
  {profile_id: 2, friend_id: 1, mutual: nil},
  {profile_id: 4, friend_id: 1, mutual: nil}
])
Like.create!([
  {profile_id: 1, post_id: 8},
  {profile_id: 1, post_id: 9},
  {profile_id: 1, post_id: 10},
  {profile_id: 1, post_id: 7},
  {profile_id: 2, post_id: 5},
  {profile_id: 4, post_id: 5},
  {profile_id: 1, post_id: 16},
  {profile_id: 4, post_id: 6},
  {profile_id: 1, post_id: 6}
])
View.create!([
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 2, viewed_id: 2},
  {profile_id: 2, viewed_id: 2},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 1, viewed_id: 2},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 2, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 4},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 1, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 4, viewed_id: 1},
  {profile_id: 1, viewed_id: 4}
])
ProfileTag.create!([
  {profile_id: 2, tag_id: 4},
  {profile_id: 2, tag_id: 5},
  {profile_id: 4, tag_id: 1},
  {profile_id: 4, tag_id: 6},
  {profile_id: 4, tag_id: 2},
  {profile_id: 1, tag_id: 11},
  {profile_id: 1, tag_id: 12},
  {profile_id: 1, tag_id: 13},
  {profile_id: 1, tag_id: 14}
])
Share.create!([
  {post_id: 5, profile_id: 1},
  {post_id: 10, profile_id: 1},
  {post_id: 5, profile_id: 4},
  {post_id: 5, profile_id: 1}
])
Comment.create!([
  {profile_id: 1, post_id: 8, description: "ok cool"},
  {profile_id: 1, post_id: 8, description: "sweet"},
  {profile_id: 1, post_id: 8, description: "awesome"},
  {profile_id: 1, post_id: 8, description: "noice"},
  {profile_id: 1, post_id: 8, description: "great"},
  {profile_id: 1, post_id: 8, description: "super"},
  {profile_id: 1, post_id: 8, description: "epic"},
  {profile_id: 1, post_id: 6, description: "black hole, cool"},
  {profile_id: 1, post_id: 5, description: "lalalla"},
  {profile_id: 1, post_id: 10, description: "great photo"},
  {profile_id: 1, post_id: 7, description: "great"},
  {profile_id: 1, post_id: 7, description: "sweet"},
  {profile_id: 1, post_id: 7, description: "sweet"},
  {profile_id: 1, post_id: 7, description: "sweet"},
  {profile_id: 1, post_id: 7, description: "great"},
  {profile_id: 1, post_id: 7, description: "nice"},
  {profile_id: 1, post_id: 6, description: "great"},
  {profile_id: 1, post_id: 6, description: "sweet"},
  {profile_id: 1, post_id: 6, description: "nice"},
  {profile_id: 1, post_id: 6, description: "ok"},
  {profile_id: 1, post_id: 6, description: "no"},
  {profile_id: 1, post_id: 6, description: "greaaaa"},
  {profile_id: 1, post_id: 5, description: "noice"},
  {profile_id: 1, post_id: 5, description: "sweet"},
  {profile_id: 2, post_id: 5, description: "nice"},
  {profile_id: 4, post_id: 5, description: "rock on"},
  {profile_id: 1, post_id: 6, description: "awesome!!"}
])
