require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ViewsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # View. As you add validations to View, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ViewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all views as @views" do
      view = View.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:views)).to eq([view])
    end
  end

  describe "GET #show" do
    it "assigns the requested view as @view" do
      view = View.create! valid_attributes
      get :show, {:id => view.to_param}, valid_session
      expect(assigns(:view)).to eq(view)
    end
  end

  describe "GET #new" do
    it "assigns a new view as @view" do
      get :new, {}, valid_session
      expect(assigns(:view)).to be_a_new(View)
    end
  end

  describe "GET #edit" do
    it "assigns the requested view as @view" do
      view = View.create! valid_attributes
      get :edit, {:id => view.to_param}, valid_session
      expect(assigns(:view)).to eq(view)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new View" do
        expect {
          post :create, {:view => valid_attributes}, valid_session
        }.to change(View, :count).by(1)
      end

      it "assigns a newly created view as @view" do
        post :create, {:view => valid_attributes}, valid_session
        expect(assigns(:view)).to be_a(View)
        expect(assigns(:view)).to be_persisted
      end

      it "redirects to the created view" do
        post :create, {:view => valid_attributes}, valid_session
        expect(response).to redirect_to(View.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved view as @view" do
        post :create, {:view => invalid_attributes}, valid_session
        expect(assigns(:view)).to be_a_new(View)
      end

      it "re-renders the 'new' template" do
        post :create, {:view => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested view" do
        view = View.create! valid_attributes
        put :update, {:id => view.to_param, :view => new_attributes}, valid_session
        view.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested view as @view" do
        view = View.create! valid_attributes
        put :update, {:id => view.to_param, :view => valid_attributes}, valid_session
        expect(assigns(:view)).to eq(view)
      end

      it "redirects to the view" do
        view = View.create! valid_attributes
        put :update, {:id => view.to_param, :view => valid_attributes}, valid_session
        expect(response).to redirect_to(view)
      end
    end

    context "with invalid params" do
      it "assigns the view as @view" do
        view = View.create! valid_attributes
        put :update, {:id => view.to_param, :view => invalid_attributes}, valid_session
        expect(assigns(:view)).to eq(view)
      end

      it "re-renders the 'edit' template" do
        view = View.create! valid_attributes
        put :update, {:id => view.to_param, :view => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested view" do
      view = View.create! valid_attributes
      expect {
        delete :destroy, {:id => view.to_param}, valid_session
      }.to change(View, :count).by(-1)
    end

    it "redirects to the views list" do
      view = View.create! valid_attributes
      delete :destroy, {:id => view.to_param}, valid_session
      expect(response).to redirect_to(views_url)
    end
  end

end
